import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import Link from 'next/link'
export default function Home() {
  const [propsObj, setPropsObj] = useState(null)
  useEffect(()=>{
    let storage = window.localStorage.getItem("proposals")
     if(!storage){
      localStorage.setItem("proposals",JSON.stringify(Obj))
      storage = localStorage.getItem("proposals")
    }
    setPropsObj(JSON.parse(storage))

  },[])
          
          

  return (
    <div className={styles.container}>
      <Head>
        <title>Proposals</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to  <Link href="/">Choice Proposals</Link>
        </h1>

        <p className={styles.description}>
          Get started by viewing Proposals{' '}
          <code className={styles.code}>Here</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          {propsObj && propsObj.map(({name, desc}, key)=>{
              return (<a key={key} href="https://nextjs.org/docs" className={styles.card}>
                 <h2>{name} &rarr;</h2>
                 <p>
                  {desc}
                 </p>
               </a>);
          })}

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

const Obj = [
  {
    name: "prince",
    desc: "Welcome to the wild wild west",
  },
  {
    name: "prince",
    desc: "Welcome to the wild wild west",
  },
  {
    name: "prince",
    desc: "Welcome to the wild wild west",
  },
];